name: Build NixOS RaspberryPi Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-sdcard-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm
          install_url: https://releases.nixos.org/nix/nix-2.25.5/install

      - name: Setup QEMU for ARM emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build SD card image
        run: |
          nix build --extra-experimental-features "nix-command flakes" ./nixos/flake.nix#packages.aarch64-linux.sdcard

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdcard-image
          path: result/*
          retention-days: 7
